# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a671f4f4f1ec0f3f6abd791ca5c4871cdca385efd997a15a9a6b0fec9d2096fa68854166cc92d636234c2eb895c71ea3d024926c0aded939cf7c3f7291878a73

test:
  secret_key_base: bcadc1b74244fc78841a5cb0cc4c6705bb48b7bd4509b907d50adadecf1da3eb49e7b9b5571505340840f5be34421ac0c5d36d2ef4eb20d3bb0cd5addc68ca9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
